name: Manual pack to nuget

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Package Version"
        required: true 
        type: string

jobs:
  pack-push-nuget-package:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'tdesign-blazor'
    steps:
      - name: 迁出代码
        uses: actions/checkout@v2

      - name: Setup .NET Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - name: 发布 nuget 包
        run: |
          dotnet build
          dotnet pack ./src/TDesign/TDesign.csproj -c release -o ./pack -p:PackageVersion=${{ github.event.inputs.version }}
          dotnet nuget push './pack/*.nupkg' -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate

    
